"""File to house all the `Constants`"""

# Error codes
STATUS_REQUEST_SUCCESS = "200"
STATUS_REQUEST_CREATED = "201"
STATUS_ACCEPTED_REQUEST = "202"
STATUS_BAD_REQUEST = "400"
STATUS_UNAUTHORIZED = "401"
STATUS_ACCESS_FORBIDDEN = "403"
STATUS_NOT_FOUND = "404"
STATUS_NOT_ALLOWED = "405"
STATUS_SERVER_ERROR = "500"
STATUS_NOT_IMPLEMENTED = "501"
STATUS_BAD_GATEWAY = "502"
