"""File to house all the `Helper` functions"""

def get_all_users(token : str) -> None :...

def send_credit_user(sender : str, receiver : str, amount : float,token : str )-> bool:...

def register_new_users()->bool:...

def get_user_balance(token : str)-> float : ...

def update_user_balance(user_name : str,amount : float, token : str)->  float: ...

def request_credit_user(sender : str, receiver : str, amount : float,token : str ) -> bool:...